pipeline:
  build:
    group: test
    image: node:latest
    commands:
      - export MONGO_URL="mongodb://mongo:27017"
      - npm install
      - npm install -g jest
      - MONGO_URL="mongodb://mongo:27017" jest  --forceExit
  npm_auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      branch: master
      event: push
  publish:
    image: node:latest
    commands:
      - npm run build
      - node version.js
      - npm publish
    when:
      branch: master
      event: push

services:
  mongo:
    image: mongo:3.0
    command: [ --smallfiles ] 
