pipeline:
  ping:
    group: test
    image: mongo:3.0
    commands:
      - sleep 15
  build:
    group: test
    image: node:${NODE_VERSION}
    commands:
      - export MONGO_URL="mongodb://mongo:27017"
      - npm install
      - npm install -g jest
      - MONGO_URL="mongodb://mongo:27017" jest
  npm_auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      branch: master
  publish:
    image: node:latest
    commands:
      - node version.js
      - npm publish
    when:
      branch: master

services:
  localhost:
    image: mongo:3.0
    command: [ --smallfiles ]

matrix:
  NODE_VERSION:
    - 7
    - 8
    - 9
